<?php
// @codingStandardsIgnoreFile
/**
 * @var \Zend\Form\FormInterface $form
 */
?>
<strong>Module:</strong>        ZendSkeletonModule &raquo;
<strong>Controller:</strong>    Skeleton &raquo;
<strong>Action:</strong>        index


<?= $this->form()->openTag($form); ?>

<?php foreach ($form->getIterator() as $element): ?>
    <?= $this->formRow($element); ?>
    <br />
<?php endforeach; ?>

<?= $this->form()->closeTag($form); ?>
